version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: aluno_online_2025_1_back_end_projeto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: aluno_online_2025_1_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
